[tool.poetry]
name = "file-ingestor"
version = "0.1.0"
description = ""
authors = ["VpgMackan <dev@mndev.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pika = "^1.3.2"
boto3 = "^1.39.3"
dotenv = "^0.9.9"
langchain-text-splitters = "^0.3.8"
pgvector = "^0.4.1"
sqlalchemy = "^2.0.41"
psycopg2-binary = "^2.9.10"
pymupdf = "^1.26.3"
requests = "^2.32.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
