[tool.poetry]
name = "summary-generator"
version = "0.1.0"
description = ""
authors = ["VpgMackan <dev@mndev.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.scripts]
summary = "summary_generator.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
