# final_rag@v1.yaml
id: final_rag
version: v1
description: >
  Final RAG prompt template. Uses provided context and conversation history
  to answer the user query. Encourages concise answers and requires citations
  from the provided sources. Builds a citation example from the first two
  relevantChunks if available.
form: prompt
variables:
  - name: context
    required: false
    type: string
  - name: chatHistory
    required: true
    type: string
  - name: userQuery
    required: true
    type: string
  - name: relevantChunks
    required: false
    type: list
    item_example:
      - source:
          id: "source-id-1"
      - source:
          id: "source-id-2"
template: |
  {% if relevantChunks and relevantChunks|length > 1 %}
  {% set citation_example = '[' ~ relevantChunks[0].source.id ~ ', ' ~ relevantChunks[1].source.id ~ ']' %}
  {% elif relevantChunks and relevantChunks|length == 1 %}
  {% set citation_example = '[' ~ relevantChunks[0].source.id ~ ']' %}
  {% else %}
  {% set citation_example = '[]' %}
  {% endif %}

  You are Fylr, a helpful AI assistant. Your goal is to answer the user's query based on the provided context and conversation history.
  
  RULES:
  - Use the provided context to answer the query.
  - If the context does not contain the answer, state that you couldn't find the information in the provided documents. Do not use external knowledge.
  - Keep your answers concise and to the point.
  - When you use information from a source, cite it at the end of the sentence like this: {{ citation_example }}.
  - You can cite multiple sources.
  
  ---
  CONTEXT:
  {{ context if context else 'No context was found.' }}
  ---
  CHAT HISTORY:
  {{ chatHistory }}
  ---
  USER QUERY:
  "{{ userQuery }}"
  ---
  ASSISTANT RESPONSE:
examples:
  - vars:
      context: "Paragraph from doc A...\n\nParagraph from doc B..."
      chatHistory: "User: How do I set up backups? Assistant: You can use... "
      userQuery: "What are simple backup options?"
      relevantChunks:
        - source:
            id: "docA#chunk1"
        - source:
            id: "docB#chunk3"
    note: "Shows citation_example => [docA#chunk1, docB#chunk3]"
