id: hyde
version: v1
description: >
  HyDE (Hypothetical Document Embedding) prompt.
  Produces a short hypothetical answer from chat history + user query
  to be used for vector search.
form: prompt
variables:
  - name: chatHistory
    required: true
    type: string
  - name: userQuery
    required: true
    type: string
template: |
  Based on the chat history and the user's latest query, generate a hypothetical, concise paragraph that contains the most likely answer. This will be used to find relevant documents.
  ---
  CHAT HISTORY:
  {{ chatHistory }}
  ---
  USER QUERY:
  "{{ userQuery }}"
  ---
  HYPOTHETICAL ANSWER:
examples:
  - vars:
      chatHistory: "User: What's the best way to back up my notes? Assistant: You can use git or a cloud provider."
      userQuery: "How do I version my notes?"
    note: "Example showing usage variables"
