# summary@v1.yaml
id: summary
version: v1
description: >
  Generates a comprehensive summary for a given title based on a list of documents.
form: prompt
variables:
  - name: documents
    required: true
    type: list
    item_example:
      - name: "doc1.txt"
        content: "Content of doc 1..."
  - name: summary_title
    required: true
    type: string
template: |
  {% set formatted_docs = [] %}
  {% for doc in documents %}
  {%   set formatted_doc = "<document name='" ~ doc.name ~ "'>\n" ~ doc.content ~ "\n</document>" %}
  {%   set _ = formatted_docs.append(formatted_doc) %}
  {% endfor %}
  
  You are an expert content summarizer. Your task is to generate a comprehensive summary based on the provided documents.
  
  **Instructions:**
  1.  Read all the provided documents carefully.
  2.  Synthesize the information to create a detailed, well-structured summary for the topic: "{{ summary_title }}".
  3.  The summary should be in Markdown format.
  4.  Do not include any information that is not present in the provided documents.
  5.  If the documents are empty or do not contain relevant information, state that a summary could not be generated.
  
  **Provided Documents:**
  ---
  {{ formatted_docs | join('\n\n') if documents else 'No documents provided.' }}
  ---
  
  **Generated Summary:**